config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  resources :comments
  resources :types
  resources :categories
  root 'static_pages#home'
  get  '/aboutus',    to: 'static_pages#aboutus'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'contact',  to: 'contact#index'
  post 'contact/confirm',  to: 'contact#confirm'
  post 'contact/thanks',  to: 'contact#thanks'
  get   '/typeahead' => 'items#typeahead_action'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :items
  resources :updates
  resources :reviews
  resources :relationships,       only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.simple_import(path: '', col_sep: ',')
    a = []
    CSV.foreach(path, headers: true, col_sep: col_sep) do |r|
      a << self.new(get_import_params(r))
    end
    import a # activerecord-importのメソッドです。
  end

private
  def self.get_import_params(row)
    headers = row.headers & self.column_names # 存在するカラム名のみに限定する
    headers.each_with_object({}) do |c, h|
      h[c.to_sym] = row.field(c)
    end
  end  
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user  
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX ,:message => 'メールアドレスを入力してください'}
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews
  belongs_to :type
  belongs_to :category
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    mount_uploader :picture, PictureUploader
    validates :user_id, presence: true
    validates :content, presence: true
    belongs_to :item
    validates :item_id,  presence: true
    validate  :picture_size
    validates :title, presence: true
    validates :point, presence: true
    validates :payment, presence: true
#    validates :point,  presence: true, inclusion: { in: %w(1,2,3,4,5), message: "1から5で評価してください" }
    has_many  :comments

private
  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "5MB以下の画像にしてください")
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items
end

app/models/update.rb
class Update < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many  :comments

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
  SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
  update_attribute(:remember_digest, nil)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
   Review.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "研究機材.com"
    if page_title.empty?
      "研究機材を" + base_title + "で共同購入・クラウドファンディング"
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/items_helper.rb
module ItemsHelper

def latest_item
@item = Item.first(3)
end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def latest_review
    @reviews = Review.first(3)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
  session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
  !current_user.nil?
  end

  def log_out
  session.delete(:user_id)
  @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
  def latest_update
  @update = Update.first(3)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_comment_form.html.erb
<% if logged_in? %>
<%= form_for(@comment) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "参加コメントまたは質問を記入してください" %>
    <%= f.number_field :price, placeholder: "支払い可能額を記入してください。質問は記入なし" %>
    <%= f.hidden_field :review_id, value: review.id %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<% else %>
<div class="text-right">
  <span>質問・入札には会員登録が必要です</span>
  <li class="btn btn-primary"><%= link_to "会員登録 ＞", signup_path %></li>
</div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="reviews">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_review_form.html.erb
<%= javascript_include_tag "autocomp" %>

<%= form_for(@review) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <span>タイトル</span>
    <%= f.text_area :title, placeholder: "分かりやすい案件タイトルをつけてください" %>
    <span>応募文</span>
    <%= f.text_area :content, placeholder: "出せる上限金額や設置予定場所など、条件の詳細を書いてください" %>
    <span>対象の機材</span>
    <%= f.text_field :item_id, class: "form-control typeahead", id: "item_title" %>

    <span>必要金額・購入価格</span>
    <%= f.number_field :point %>
    <span>自身が払える金額</span>
    <%= f.number_field :payment %>

  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<h2><%= current_user.name %></h2>
<span><%= link_to "プロフィールへ", current_user %></span>
<span><%= pluralize(current_user.reviews.count, "review") %></span>