config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  resources :comments
  resources :types
  resources :categories
  root 'static_pages#home'
  get  '/aboutus',    to: 'static_pages#aboutus'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'contact',  to: 'contact#index'
  post 'contact/confirm',  to: 'contact#confirm'
  post 'contact/thanks',  to: 'contact#thanks'
  get   '/typeahead' => 'items#typeahead_action'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :items
  resources :updates
  resources :reviews
  resources :relationships,       only: [:create, :destroy]
end

app/models/update.rb
class Update < ApplicationRecord
end

app/controllers/updates_controller.rb
class UpdatesController < ApplicationController
  before_action :set_update, only: [:show, :edit, :update, :destroy]

  # GET /updates
  # GET /updates.json
  def index
    @updates = Update.paginate(page: params[:page])
  end

  # GET /updates/1
  # GET /updates/1.json
  def show
  end

  # GET /updates/new
  def new
    @update = Update.new
  end

  # GET /updates/1/edit
  def edit
  end

  # POST /updates
  # POST /updates.json
  def create
    @update = Update.new(update_params)

    respond_to do |format|
      if @update.save
        format.html { redirect_to @update, notice: 'Update was successfully created.' }
        format.json { render :show, status: :created, location: @update }
      else
        format.html { render :new }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /updates/1
  # PATCH/PUT /updates/1.json
  def update
    respond_to do |format|
      if @update.update(update_params)
        format.html { redirect_to @update, notice: 'Update was successfully updated.' }
        format.json { render :show, status: :ok, location: @update }
      else
        format.html { render :edit }
        format.json { render json: @update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updates/1
  # DELETE /updates/1.json
  def destroy
    @update.destroy
    respond_to do |format|
      format.html { redirect_to updates_url, notice: 'Update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_update
      @update = Update.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def update_params
      params.require(:update).permit(:title, :content)
    end
end

app/helpers/updates_helper.rb
module UpdatesHelper
  def latest_update
  @update = Update.first(3)
  end
end

app/views/updates/_form.html.erb
<%= form_with(model: update, local: true) do |form| %>
  <% if update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(update.errors.count, "error") %> prohibited this update from being saved:</h2>

      <ul>
      <% update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/updates/edit.html.erb
<h1>Editing Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Show', @update %> |
<%= link_to 'Back', updates_path %>

app/views/updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Updates</h1>
<%= will_paginate %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @updates.each do |update| %>
      <tr>
        <td><%= update.title %></td>
        <td><%= update.content %></td>
        <td><%= link_to 'Show', update %></td>
        <td><%= link_to 'Edit', edit_update_path(update) %></td>
        <td><%= link_to 'Destroy', update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>
<br>

<%= link_to 'New Update', new_update_path %>

app/views/updates/new.html.erb
<h1>New Update</h1>

<%= render 'form', update: @update %>

<%= link_to 'Back', updates_path %>

app/views/updates/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @update.title %>
</h1>

<p>
  <%= @update.content %>
</p>