config/routes.rb
Rails.application.routes.draw do
  get 'contact/index'
  resources :comments
  resources :types
  resources :categories
  root 'static_pages#home'
  get  '/aboutus',    to: 'static_pages#aboutus'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'contact',  to: 'contact#index'
  post 'contact/confirm',  to: 'contact#confirm'
  post 'contact/thanks',  to: 'contact#thanks'
  get   '/typeahead' => 'items#typeahead_action'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :items
  resources :updates
  resources :reviews
  resources :relationships,       only: [:create, :destroy]
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items  
end

app/controllers/categories_controller.rb
require 'csv'
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy,:items]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @items = @category.items.paginate(page: params[:page])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    if params[:category]
    @category = Category.new(category_params)

    respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render :show, status: :created, location: @category }
        else
          format.html { render :new }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    else
      registered_count = import_categories
      redirect_to categories_path, notice: "#{registered_count}件登録しました"
    end

  end
  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import_categories
    # 登録処理前のレコード数
    current_category_count = ::Category.count
    categories = []
    # windowsで作られたファイルに対応するので、encoding: "SJIS"を付けている
    CSV.foreach(params[:categories_file].path, headers: true) do |row|
      categories << ::Category.new({ name: row[0], description: row[1], ancestry: row[2]})
    end
    # importメソッドでバルクインサートできる
    ::Category.import(categories)
    # 何レコード登録できたかを返す
    ::Category.count - current_category_count
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :ancestry)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :ancestry %>
    <%= form.text_field :ancestry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1>機材カテゴリー（顕微鏡・冷凍庫など）から探す</h1>
</div>
  <% breadcrumb :categories %>
<ul class="list-group">
    <% @categories.each do |category| %>
        <li class="list-group-item">
          <%= link_to category.name, category %>
          (<%= category.items.count %>)
        <% if logged_in? && current_user.admin?%>
          | <%= link_to 'Edit', edit_category_path(category) %>
          | <%= link_to "delete", category, method: :delete,
                                        data: { confirm: "本当に削除しますか" } %>
        <% end %>
        </li>
    <% end %>
  </ul>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

<% if flash[:notice] %>
  <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>

<div>
  <%= form_tag categories_path, method: :post, multipart: true do |f| %>
    <div class="search_item">
      <%= text_field_tag 'filename',"", id: "filename", disabled: true %>
      <%= file_field_tag 'categories_file', id: "file_input", style: "display: none;", onchange: "file_selected($(this));" %>
      <%= button_tag 'ファイル選択', class: %i(btn-primary csv_input_btn), type: 'button', onclick: "$('#file_input').click();" %>
    </div>
    <div>
      <button type="submit" class="btn btn-primary">CSVインポート</button>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  function file_selected(file_field){
    var filename = $(file_field)[0].files[0].name;
    $("#filename").val(filename);
  }
</script>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
<div class="page-header">
  <h1><%= @category.name %>の関連商品一覧 (<%= @category.items.count %>)</h1>
</div>
  <% breadcrumb :category, @category %>
<p class="description"> <%= @category.description %></p>
<% if @category.items.any? %>
<div class="container">
  <ul class="row row-eq-height">
    <%= render @items %>
  </ul>
</div>
  <%= will_paginate @items %>
<% end %>